modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="gun_mod_mark1"
version="1.0.0"
displayName="gun mod mark1"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jonathonferguson, MCreator"

[[dependencies.gun_mod_mark1]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



